[tool.poetry]
name = "bilibili_getreceivedgiftstream"
version = "0.6.3"
description = "登录并获取bilibili账号某段时间礼物流水"
authors = ["铂屑 <1824390830@qq.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
qrcode = "^7.3.1"
requests = "^2.28.1"
Pillow = "^9.2.0"
aiohttp = "^3.8.1"
xlwt = "^1.3.0"
colorama = "^0.4.5"

[tool.poetry.dev-dependencies]
pyinstaller = "^5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true
